version: '3.9'

name: 'wavechat'

networks:
  wavechat-dev:
    driver: bridge

services:
  postgres_db:
    image: postgres:latest

    container_name: postgres
    
    environment:
      POSTGRES_NAME: 'postgres'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'CorporateMessanger'

    ports:
      - "5432:5432"
    
    networks:
      - wavechat-dev
    
    volumes:
      - postgres-data:/var/lib/postgresql/data

  authorization_service:
    image: ${DOCKER_REGISTRY-}wavechat-authorization
    container_name: wavechat-auth-service
    build:
      context: .
      dockerfile: /src/Systems/Api/WaveChat.Authorization/Dockerfile
    networks: 
      - wavechat-dev
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - postgres_db
    # env_file:
    #   - env.authorization

volumes:
  postgres-data: